project:
  type: website
  output-dir: _site

website:
  title: "Natasha Kang"
  site-url: "https://natkang.github.io"
  navbar:
    left:
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
