---
title: "Econometrics (Chow)"
---

## Lecture Notes

- [Lecture 0: Introduction](/files/teaching/econometrics-chow/intro.html)
- [Lecture 1: Causality](/files/teaching/econometrics-chow/lect1_causality.html)
- [Lecture 2a: The Linear Regression Model](/files/teaching/econometrics-chow/lect2a_lrm_intro.html)
- [Lecture 2b: Linear Regression — Estimation](/files/teaching/econometrics-chow/lect2b_estimation.html)
- [Lecture 2c: Properties of OLS Estimators](/files/teaching/econometrics-chow/lect2c_estimator_properties.html)
- [Lecture 3a: Inference](/files/teaching/econometrics-chow/lect3a_inference.html)
- [Lecture 3b: Asymptotics & Heteroskedasticity](/files/teaching/econometrics-chow/lect3b_asymptotics_heteroskedasticity.html)
- [Lecture 4a: Functional Form & Scaling](/files/teaching/econometrics-chow/lect4a_functional_form_scaling.html)
- [Lecture 4b: Dummy Variables](/files/teaching/econometrics-chow/lect4b_dummy_variables.html)
- [Lecture 4c: Model Selection & Controls](/files/teaching/econometrics-chow/lect4c_model_selection_controls.html)
- [Lecture 5a: IV — Motivation](/files/teaching/econometrics-chow/lect5a_iv_motivation.html)
- [Lecture 5b: IV — Estimation](/files/teaching/econometrics-chow/lect5b_iv_estimation.html)
- [Lecture 6a: Panel Regression](/files/teaching/econometrics-chow/lect6a_panel_regression.html)
